# регистрация нового пользователя
POST http://127.0.0.1:8080/register/
Content-Type: application/json

{
  "username": "userpeep",
  "password": "1234fF#1D",
  "email": "my_maialzs@mail.ru"
}

###
# получение токена по имени/почте и паролю
GET http://127.0.0.1:8080/get-token/
Content-Type: application/json

{
  "username": "userpp",
  "password": "1234fF#1D"
}

###
# создание объявления
POST http://127.0.0.1:8080/advertisements/
Content-Type: application/json
Authorization: Token 8d98773b-ef39-4710-8ffe-005d823db224

{
  "title": "new_adv",
  "description":"description"
}

###
# получить объявления
GET http://127.0.0.1:8080/advertisements/
Content-Type: application/json

###
# получить одно объявление
GET http://127.0.0.1:8080/advertisements/4/
Content-Type: application/json


###
# удалить объявление
DELETE http://127.0.0.1:8080/advertisements/4/
Content-Type: application/json
Authorization: Token 8d98773b-ef39-4710-8ffe-005d823db224