# регистрация нового пользователя
POST http://127.0.0.1:8080/register/
Content-Type: application/json

{
  "username": "user2",
  "password": "1234fF#1D",
  "email": "customs_mail@yandex.ru"
}

###
# получение токена по имени/почте и паролю
GET http://127.0.0.1:8080/get-token/
Content-Type: application/json

{
  "username": "user1",
  "password": "1234fF#1D"
}

###
# создание объявления
POST http://127.0.0.1:8080/advertisements/
Content-Type: application/json
Authorization: Token 0de81058-bed8-4ba0-be09-6c6eb70bbbb7

{
  "title": "new_adv",
  "description":"description"
}

###
# обновить объявление
PATCH http://127.0.0.1:8080/advertisements/2/
Content-Type: application/json
Authorization: Token 0de81058-bed8-4ba0-be09-6c6eb70bbbb7

{
  "title": "updated title",
  "description":"updated description"
}

###
# получить объявления
GET http://127.0.0.1:8080/advertisements/
Content-Type: application/json

###
# получить одно объявление
GET http://127.0.0.1:8080/advertisements/2/
Content-Type: application/json


###
# удалить объявление
DELETE http://127.0.0.1:8080/advertisements/7/
Content-Type: application/json
Authorization: Token 0de81058-bed8-4ba0-be09-6c6eb70bbbb7